In [3]:
include("utils.jl")

mprint (generic function with 1 method)

In [4]:
ent = example_bound_entangled(0.5)

9×9 Matrix{Float64}:
 0.1  0.0  0.0  0.0  0.1  0.0  0.0        0.0  0.1
 0.0  0.1  0.0  0.0  0.0  0.0  0.0        0.0  0.0
 0.0  0.0  0.1  0.0  0.0  0.0  0.0        0.0  0.0
 0.0  0.0  0.0  0.1  0.0  0.0  0.0        0.0  0.0
 0.1  0.0  0.0  0.0  0.1  0.0  0.0        0.0  0.1
 0.0  0.0  0.0  0.0  0.0  0.1  0.0        0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.15       0.0  0.0866025
 0.0  0.0  0.0  0.0  0.0  0.0  0.0        0.1  0.0
 0.1  0.0  0.0  0.0  0.1  0.0  0.0866025  0.0  0.15

In [5]:
B(9)

9×9 Matrix{Float64}:
  0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0  -1.0
  0.0  0.0   0.0  0.0   0.0  0.0   0.0  1.0   0.0
  0.0  0.0   0.0  0.0   0.0  0.0  -1.0  0.0   0.0
  0.0  0.0   0.0  0.0   0.0  1.0   0.0  0.0   0.0
  0.0  0.0   0.0  0.0  -1.0  0.0   0.0  0.0   0.0
  0.0  0.0   0.0  1.0   0.0  0.0   0.0  0.0   0.0
  0.0  0.0  -1.0  0.0   0.0  0.0   0.0  0.0   0.0
  0.0  1.0   0.0  0.0   0.0  0.0   0.0  0.0   0.0
 -1.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0   0.0

In [7]:
using LinearAlgebra
using MosekTools
using JLD2
using ProgressMeter
using Ket

In [17]:
tr(B(9) * rand_sep(3, 3))

-9.085575020926546

In [9]:
tr(B(9) * ent)

-0.30000000000000004

In [9]:
rationalize.(ent)

9×9 Matrix{Rational{Int64}}:
 1//10   0      0      0     1//10   0     …   0            1//10
  0     1//10   0      0      0      0         0             0
  0      0     1//10   0      0      0         0             0
  0      0      0     1//10   0      0         0             0
 1//10   0      0      0     1//10   0         0            1//10
  0      0      0      0      0     1//10  …   0             0
  0      0      0      0      0      0         0     14571884//168261623
  0      0      0      0      0      0        1//10          0
 1//10   0      0      0     1//10   0         0            3//20

In [12]:
entanglement_robustness(ent)

(3.832689735028261e-9, [0.12727272779205043 2.3407770983800667e-17 … 1.181473511412514e-11 -0.14025973564881208; 2.3407770983800667e-17 0.1000000016716722 … -7.272111479891501e-12 4.625417818488384e-12; … ; 1.181473511412514e-11 -7.272111479891501e-12 … 0.1000000017579168 2.6704848065433812e-12; -0.14025973564881208 4.625417818488384e-12 … 2.6704848065433812e-12 0.13766233471739547])

In [112]:
r, w = entanglement_robustness(ent, [3, 3], 2, noise="separable"; solver=Mosek.Optimizer)

(0.001829203442194528, [0.004280136815258669 2.300099003843447e-21 … 4.945748494529241e-22 -0.04196695629167429; 2.300099003843447e-21 0.055811278001551716 … -0.015493104792338393 -8.145054599372767e-21; … ; 4.945748494529241e-22 -0.015493104792338393 … 0.07078260594835498 7.055910432407977e-21; -0.04196695629167429 -8.145054599372767e-21 … 7.055910432407977e-21 0.04135083972520054])

In [113]:
w = rationalize.(w, tol=1e-5)

9×9 Matrix{Rational{Int64}}:
  1//234      0      -1//10451  …    0       1//354     0      -6//143
   0        12//215    0             0        0       -7//452    0
 -1//10451    0      17//290         0       1//1519    0      11//322
   0          0        0            2//201    0         0        0
 -5//64       0      -2//253         0       7//375     0      -9//92
   0          0        0        …  23//482    0         0        0
  1//354      0       1//1519        0      32//683     0      -4//91
   0        -7//452    0             0        0       31//438    0
 -6//143      0      11//322         0      -4//91      0      11//266

In [ ]:
for _ in 1:10000000
    xy = kron(randn(3), randn(3))
    if xy' * w * xy < 0
        @show xy' * w * xy
        @show xy
        break
    end
end

xy' * B(9) * xy = -1.9907309584486097
xy = [0.15501076552929685, -0.5790199187137186, -0.19724261878024305, -0.14931695941451767, 0.5577515433044764, 0.18999756567008502, -0.3173045902896285, 1.1852446341365015, 0.40375252729069144]


In [63]:
tr(w * ent)

-0.0014282032302755064

In [121]:
files_3x3 = [
    "../pncp_forms_3x3.jld2",
]

forms_3x3 = vcat([jldopen(file) do file
    vcat([file[k] for k in keys(file)]...)
end for file in files_3x3]...)

100000-element Vector{Matrix{Float64}}:
 [0.08029841173603022 0.2575678418886549 … 0.18454740948257867 -0.2150853238601356; 0.2575678418886549 1.6190327227413153 … -1.0256980924993278 -0.25932227282649406; … ; 0.18454740948257867 -1.0256980924993278 … 0.780188443516995 0.6576697807855278; -0.2150853238601356 -0.25932227282649406 … 0.6576697807855278 0.7208101965248197]
 [2.3181725250143406 -0.6865246767891688 … 0.9060227701893939 0.8028285817447829; -0.6865246767891688 0.24378479022697405 … -0.4677777756883194 -0.5346244135256595; … ; 0.9060227701893939 -0.4677777756883194 … 0.9367187772842882 0.056821809775599565; 0.8028285817447829 -0.5346244135256595 … 0.056821809775599565 0.490858004332166]
 [2.2486230868731885 1.5790087097325536 … -0.3966088458214755 -0.9809138585214243; 1.5790087097325536 1.5974902035976968 … -0.7528811378714387 -0.7740535707600561; … ; -0.3966088458214755 -0.7528811378714387 … 0.3694888848488327 0.8559387088650567; -0.9809138585214243 -0.7740535707600561 … 0.855

In [137]:
f = forms_3x3[1]
for _ in 1:10000000
    xy = kron(randn(3), randn(3))
    if xy' * f * xy < 0
        @show xy' * f * xy
        @show xy
        break
    end
end

In [125]:
sort(tr.(forms_3x3 .* Ref(ent)))

100000-element Vector{Float64}:
 0.19002940826009662
 0.21100819984294927
 0.22249618070523328
 0.23364814792007674
 0.23380293169825572
 0.2347255649105194
 0.23719514787157123
 0.24017659401121244
 0.24130150445077067
 0.2427200416129861
 ⋮
 1.983564779347149
 2.0435227326127565
 2.128959066373469
 2.16670600194319
 2.625719310431346
 2.7965606561347482
 2.923404069694823
 3.1794434832959024
 3.611195877981361

In [138]:
example = [
    1/3  0.0  0.0  0.0  1/3  0.0  0.0  0.0  1/3
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    1/3  0.0  0.0  0.0  1/3  0.0  0.0  0.0  1/3
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    1/3  0.0  0.0  0.0  1/3  0.0  0.0  0.0  1/3
]

9×9 Matrix{Float64}:
 0.333333  0.0  0.0  0.0  0.333333  0.0  0.0  0.0  0.333333
 0.0       0.0  0.0  0.0  0.0       0.0  0.0  0.0  0.0
 0.0       0.0  0.0  0.0  0.0       0.0  0.0  0.0  0.0
 0.0       0.0  0.0  0.0  0.0       0.0  0.0  0.0  0.0
 0.333333  0.0  0.0  0.0  0.333333  0.0  0.0  0.0  0.333333
 0.0       0.0  0.0  0.0  0.0       0.0  0.0  0.0  0.0
 0.0       0.0  0.0  0.0  0.0       0.0  0.0  0.0  0.0
 0.0       0.0  0.0  0.0  0.0       0.0  0.0  0.0  0.0
 0.333333  0.0  0.0  0.0  0.333333  0.0  0.0  0.0  0.333333

In [140]:
sort(tr.(forms_3x3 .* Ref(example)))

100000-element Vector{Float64}:
 -1.2409856529123826
 -1.2161020655224077
 -1.1609315447992934
 -1.1319830458080415
 -1.1319797676399361
 -1.0724572348965749
 -1.072415852572257
 -1.0492022753981955
 -1.0413758771524824
 -1.0203223148082348
  ⋮
  4.027917773318825
  4.089673957092625
  4.1466896644364475
  4.230333052553129
  4.496943405177996
  4.59758262854613
  5.021717364953231
  6.1623615650684265
  7.016880138905619

In [147]:
B = [
     0  0  0  0  0  0  0  0 -1
     0  0  0  0  0  0  0  1  0
     0  0  0  0  0  0 -1  0  0
     0  0  0  0  0  1  0  0  0
     0  0  0  0 -1  0  0  0  0
     0  0  0  1  0  0  0  0  0
     0  0 -1  0  0  0  0  0  0
     0  1  0  0  0  0  0  0  0
    -1  0  0  0  0  0  0  0  0
]

9×9 Matrix{Int64}:
  0  0   0  0   0  0   0  0  -1
  0  0   0  0   0  0   0  1   0
  0  0   0  0   0  0  -1  0   0
  0  0   0  0   0  1   0  0   0
  0  0   0  0  -1  0   0  0   0
  0  0   0  1   0  0   0  0   0
  0  0  -1  0   0  0   0  0   0
  0  1   0  0   0  0   0  0   0
 -1  0   0  0   0  0   0  0   0

In [162]:
function _B(d::Int)
    b = zeros(d, d)
    for k in 1:d
        b[k, end-k+1] = (-1)^k
    end
    return b
end

_B (generic function with 1 method)

In [163]:
_B(9)

9×9 Matrix{Float64}:
  0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0  -1.0
  0.0  0.0   0.0  0.0   0.0  0.0   0.0  1.0   0.0
  0.0  0.0   0.0  0.0   0.0  0.0  -1.0  0.0   0.0
  0.0  0.0   0.0  0.0   0.0  1.0   0.0  0.0   0.0
  0.0  0.0   0.0  0.0  -1.0  0.0   0.0  0.0   0.0
  0.0  0.0   0.0  1.0   0.0  0.0   0.0  0.0   0.0
  0.0  0.0  -1.0  0.0   0.0  0.0   0.0  0.0   0.0
  0.0  1.0   0.0  0.0   0.0  0.0   0.0  0.0   0.0
 -1.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0   0.0

In [151]:
tr(B * ent)

-0.30000000000000004

In [ ]:
function gen_ppt_ent(n::Int, m::Int, forms; n_trials::Int=10000, tol::Float64=1e-6, rng=Random.GLOBAL_RNG, rand_vec=rand_vec)
    @showprogress for i in 1:n_trials
        ppt = rand_ppt(n, m; rng, rand_vec)
        r, idx = findmin(dot.(forms, Ref(ppt)))
        if r < -tol
            println("Witness $idx detects entanglement: $r")
            return ppt, forms[idx]
        end
    end
    return nothing, nothing
end

In [ ]:
function test_ppt2_pncp(n::Int, m::Int, forms; n_trials::Int=10000, tol::Float64=1e-6)
    @showprogress for i in 1:n_trials
        ppt = rationalize.(ppt2.rand_ppt(n, m), tol=1)
        cpp = ampliation(ppt, ppt, n, m)
        r, idx = findmin(tr.(forms .* Ref(cpp)))
        if r < -tol
            println("Witness $idx detects entanglement: $r")
            return ppt, forms[idx]
        end
    end
    return nothing, nothing
end

In [24]:
rho = [
    2  0  0  0  0  0  0  0  0  0  1  0  0  0  0  1
    0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0
    0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0
    0  0  0  1  0  0  0  0  0  1  0  0  0  0  0  0
    0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0
    0  0  0  0  0  2  0  0  0  0  1  0  0  0  0  1
    0  0  0  0  0  0  1  0  0  0  0  0  1  0  0  0
    0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0
    0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0
    0  0  0  1  0  0  0  0  0  1  0  0  0  0  0  0
    1  0  0  0  0  1  0  0  0  0  2  0  0  0  0  0
    0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0
    0  0  0  0  0  0  1  0  0  0  0  0  1  0  0  0
    0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0
    0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0
    1  0  0  0  0  1  0  0  0  0  0  0  0  0  0  2
]

16×16 Matrix{Int64}:
 2  0  0  0  0  0  0  0  0  0  1  0  0  0  0  1
 0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  0  1  0  0  0  0  0  0
 0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  2  0  0  0  0  1  0  0  0  0  1
 0  0  0  0  0  0  1  0  0  0  0  0  1  0  0  0
 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  0  1  0  0  0  0  0  0
 1  0  0  0  0  1  0  0  0  0  2  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0
 0  0  0  0  0  0  1  0  0  0  0  0  1  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0
 1  0  0  0  0  1  0  0  0  0  0  0  0  0  0  2

In [59]:
tr(rho * rand_sep(4, 4))

84.6705208475533